using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class satinalmakod : MonoBehaviour
{
    int item;
    int karak;
    int ilksec;
    public GameObject paratext;
    public GameObject satinalmabuton;
    public GameObject sandik;
    public GameObject kiriksandik;
    public GameObject[] karakterler;
    public GameObject[] itemler;
    bool alindi = false;
    public GameObject okbuton;
    public GameObject konfetiler;
    void Start()
    {
        //PlayerPrefs.DeleteAll();
        //PlayerPrefs.SetInt("para", 25000);
        
        paratext.GetComponent<Text>().text = PlayerPrefs.GetInt("para").ToString();
    }

    public void satinalma() 
    {
        konfetiler.SetActive(true);
        ilksec = Random.Range(1, 3);
        Debug.Log(ilksec);
        
        if (ilksec == 1)
        {
            karak = Random.Range(1, 31);
            Debug.Log("karakter" + karak);
            if (karak == 1) { if (PlayerPrefs.GetInt("bard") == 1) { satinalma(); } if (PlayerPrefs.GetInt("bard") == 0) { PlayerPrefs.SetInt("bard", 1);PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000);Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation);Destroy(sandik);karakterler[karak].SetActive(true); alindi = true;okbuton.SetActive(true); }; }
            if (karak == 2) { if (PlayerPrefs.GetInt("blackbeard") == 1) { satinalma(); } if (PlayerPrefs.GetInt("blackbeard") == 0) { PlayerPrefs.SetInt("blackbeard", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); karakterler[karak].SetActive(true); alindi = true; okbuton.SetActive(true); };  }
            if (karak == 3) { if (PlayerPrefs.GetInt("cowboy") == 1) { satinalma(); } if (PlayerPrefs.GetInt("cowboy") == 0) { PlayerPrefs.SetInt("cowboy", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); karakterler[karak].SetActive(true); alindi = true; okbuton.SetActive(true); }; }
            if (karak == 4) { if (PlayerPrefs.GetInt("druid") == 1) { satinalma(); } if (PlayerPrefs.GetInt("druid") == 0) { PlayerPrefs.SetInt("druid", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); karakterler[karak].SetActive(true); alindi = true; okbuton.SetActive(true); }; }
            if (karak == 5) { if (PlayerPrefs.GetInt("engcaptain") == 1) { satinalma(); } if (PlayerPrefs.GetInt("engcaptain") == 0) { PlayerPrefs.SetInt("engcaptain", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); karakterler[karak].SetActive(true); alindi = true; okbuton.SetActive(true); }; }
            if (karak == 6) { if (PlayerPrefs.GetInt("geisha") == 1) { satinalma(); } if (PlayerPrefs.GetInt("geisha") == 0) { PlayerPrefs.SetInt("geisha", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); karakterler[karak].SetActive(true); alindi = true; okbuton.SetActive(true); };}
            if (karak == 7) { if (PlayerPrefs.GetInt("goblinchef") == 1) { satinalma(); } if (PlayerPrefs.GetInt("goblinchef") == 0) { PlayerPrefs.SetInt("goblinchef", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); karakterler[karak].SetActive(true); alindi = true; okbuton.SetActive(true); }; }
            if (karak == 8) { if (PlayerPrefs.GetInt("goblinshaman") == 1) { satinalma(); } if (PlayerPrefs.GetInt("goblinshaman") == 0) { PlayerPrefs.SetInt("goblinshaman", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); karakterler[karak].SetActive(true); alindi = true; okbuton.SetActive(true); }; }
            if (karak == 9) { if (PlayerPrefs.GetInt("goblinwarrior") == 1) { satinalma(); } if (PlayerPrefs.GetInt("goblinwarrior") == 0) { PlayerPrefs.SetInt("goblinwarrior", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); karakterler[karak].SetActive(true); alindi = true; okbuton.SetActive(true); };}
            if (karak == 10) { if (PlayerPrefs.GetInt("grunt") == 1) { satinalma(); } if (PlayerPrefs.GetInt("grunt") == 0) { PlayerPrefs.SetInt("grunt", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); karakterler[karak].SetActive(true); alindi = true; okbuton.SetActive(true); }; }
            if (karak == 11) { if (PlayerPrefs.GetInt("gypsy") == 1) { satinalma(); } if (PlayerPrefs.GetInt("gypsy") == 0) { PlayerPrefs.SetInt("gypsy", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); karakterler[karak].SetActive(true); alindi = true; okbuton.SetActive(true); }; }
            if (karak == 12) { if (PlayerPrefs.GetInt("iskeletor") == 1) { satinalma(); } if (PlayerPrefs.GetInt("iskeletor") == 0) { PlayerPrefs.SetInt("iskeletor", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); karakterler[karak].SetActive(true); alindi = true; okbuton.SetActive(true); };}
            if (karak == 13) { if (PlayerPrefs.GetInt("iskeletorsoldier1") == 1) { satinalma(); } if (PlayerPrefs.GetInt("iskeletorsoldier1") == 0) { PlayerPrefs.SetInt("iskeletorsoldier1", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); karakterler[karak].SetActive(true); alindi = true; okbuton.SetActive(true); }; }
            if (karak == 14) { if (PlayerPrefs.GetInt("iskeletorsoldier2") == 1) { satinalma(); } if (PlayerPrefs.GetInt("iskeletorsoldier2") == 0) { PlayerPrefs.SetInt("iskeletorsoldier2", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); karakterler[karak].SetActive(true); alindi = true; okbuton.SetActive(true); };}
            if (karak == 15) { if (PlayerPrefs.GetInt("iskeletorwarrior") == 1) { satinalma(); } if (PlayerPrefs.GetInt("iskeletorwarrior") == 0) { PlayerPrefs.SetInt("iskeletorwarrior", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); karakterler[karak].SetActive(true); alindi = true; }; okbuton.SetActive(true); }
            if (karak == 16) { if (PlayerPrefs.GetInt("king") == 1) { satinalma(); } if (PlayerPrefs.GetInt("king") == 0) { PlayerPrefs.SetInt("king", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); karakterler[karak].SetActive(true); alindi = true; okbuton.SetActive(true); }; }
            if (karak == 17) { if (PlayerPrefs.GetInt("knight") == 1) { satinalma(); } if (PlayerPrefs.GetInt("knight") == 0) { PlayerPrefs.SetInt("knight", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); karakterler[karak].SetActive(true); alindi = true; okbuton.SetActive(true); }; }
            if (karak == 18) { if (PlayerPrefs.GetInt("kuin") == 1) { satinalma(); } if (PlayerPrefs.GetInt("kuin") == 0) { PlayerPrefs.SetInt("kuin", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); karakterler[karak].SetActive(true); alindi = true; okbuton.SetActive(true); };}
            if (karak == 19) { if (PlayerPrefs.GetInt("piratecaptain") == 1) { satinalma(); } if (PlayerPrefs.GetInt("piratecaptain") == 0) { PlayerPrefs.SetInt("piratecaptain", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); karakterler[karak].SetActive(true); alindi = true; okbuton.SetActive(true); };}
            if (karak == 20) { if (PlayerPrefs.GetInt("rogue") == 1) { satinalma(); } if (PlayerPrefs.GetInt("rogue") == 0) { PlayerPrefs.SetInt("rogue", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); karakterler[karak].SetActive(true); alindi = true; okbuton.SetActive(true); };}
            if (karak == 21) { if (PlayerPrefs.GetInt("rockgolem") == 1) { satinalma(); } if (PlayerPrefs.GetInt("rockgolem") == 0) { PlayerPrefs.SetInt("rockgolem", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); karakterler[karak].SetActive(true); alindi = true; okbuton.SetActive(true); };}
            if (karak == 22) { if (PlayerPrefs.GetInt("samurai") == 1) { satinalma(); } if (PlayerPrefs.GetInt("samurai") == 0) { PlayerPrefs.SetInt("samurai", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); karakterler[karak].SetActive(true); alindi = true; okbuton.SetActive(true); };}
            if (karak == 23) { if (PlayerPrefs.GetInt("sherif") == 1) { satinalma(); } if (PlayerPrefs.GetInt("sherif") == 0) { PlayerPrefs.SetInt("sherif", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); karakterler[karak].SetActive(true); alindi = true; okbuton.SetActive(true); };}
            if (karak == 24) { if (PlayerPrefs.GetInt("sorcerer") == 1) { satinalma(); } if (PlayerPrefs.GetInt("sorcerer") == 0) { PlayerPrefs.SetInt("sorcerer", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); karakterler[karak].SetActive(true); alindi = true; okbuton.SetActive(true); };}
            if (karak == 25) { if (PlayerPrefs.GetInt("viking") == 1) { satinalma(); } if (PlayerPrefs.GetInt("viking") == 0) { PlayerPrefs.SetInt("viking", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); karakterler[karak].SetActive(true); alindi = true; okbuton.SetActive(true); };}
            if (karak == 26) { if (PlayerPrefs.GetInt("vikingwarrior") == 1) { satinalma(); } if (PlayerPrefs.GetInt("vikingwarrior") == 0) { PlayerPrefs.SetInt("vikingwarrior", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); karakterler[karak].SetActive(true); alindi = true; okbuton.SetActive(true); };}
            if (karak == 27) { if (PlayerPrefs.GetInt("villageman") == 1) { satinalma(); } if (PlayerPrefs.GetInt("villageman") == 0) { PlayerPrefs.SetInt("villageman", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); karakterler[karak].SetActive(true); alindi = true; okbuton.SetActive(true); };}
            if (karak == 28) { if (PlayerPrefs.GetInt("warrior") == 1) { satinalma(); } if (PlayerPrefs.GetInt("warrior") == 0) { PlayerPrefs.SetInt("warrior", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); karakterler[karak].SetActive(true); alindi = true; okbuton.SetActive(true); };}
            if (karak == 29) { if (PlayerPrefs.GetInt("witch") == 1) { satinalma(); } if (PlayerPrefs.GetInt("witch") == 0) { PlayerPrefs.SetInt("witch", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); karakterler[karak].SetActive(true); alindi = true; okbuton.SetActive(true); };}
            if (karak == 30) { if (PlayerPrefs.GetInt("wizard") == 1) { satinalma(); } if (PlayerPrefs.GetInt("wizard") == 0) { PlayerPrefs.SetInt("wizard", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); karakterler[karak].SetActive(true); alindi = true; okbuton.SetActive(true); };}
            if(karak > 30) { satinalma(); }
        }
        if (ilksec == 2) 
        {
            item = Random.Range(1, 25);
            Debug.Log("item" + item);
            if (item == 1) { if (PlayerPrefs.GetInt("boneaxe") == 1) { satinalma(); } if (PlayerPrefs.GetInt("boneaxe") == 0) { PlayerPrefs.SetInt("boneaxe", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); itemler[item].SetActive(true); alindi = true; okbuton.SetActive(true); };}
            if (item == 2) { if (PlayerPrefs.GetInt("crystalhalberd") == 1) { satinalma(); } if (PlayerPrefs.GetInt("crystalhalberd") == 0) { PlayerPrefs.SetInt("crystalhalberd", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); itemler[item].SetActive(true); alindi = true; okbuton.SetActive(true); }; }
            if (item == 3) { if (PlayerPrefs.GetInt("club") == 1) { satinalma(); } if (PlayerPrefs.GetInt("club") == 0) { PlayerPrefs.SetInt("club", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); itemler[item].SetActive(true); alindi = true; okbuton.SetActive(true); };}
            if (item == 4) { if (PlayerPrefs.GetInt("lute") == 1) { satinalma(); } if (PlayerPrefs.GetInt("lute") == 0) { PlayerPrefs.SetInt("lute", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); itemler[item].SetActive(true); alindi = true; okbuton.SetActive(true); }; }
            if (item == 5) { if (PlayerPrefs.GetInt("broom") == 1) { satinalma(); } if (PlayerPrefs.GetInt("broom") == 0) { PlayerPrefs.SetInt("broom", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); itemler[item].SetActive(true); alindi = true; okbuton.SetActive(true); };}
            if (item == 6) { if (PlayerPrefs.GetInt("crystalsworddouble") == 1) { satinalma(); } if (PlayerPrefs.GetInt("crystalsworddouble") == 0) { PlayerPrefs.SetInt("crystalsworddouble", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); itemler[item].SetActive(true); alindi = true; okbuton.SetActive(true); }; }
            if (item == 7) { if (PlayerPrefs.GetInt("crystalsword") == 1) { satinalma(); } if (PlayerPrefs.GetInt("crystalsword") == 0) { PlayerPrefs.SetInt("crystalsword", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); itemler[item].SetActive(true); alindi = true; okbuton.SetActive(true); };}
            if (item == 8) { if (PlayerPrefs.GetInt("naturestaff") == 1) { satinalma(); } if (PlayerPrefs.GetInt("naturestaff") == 0) { PlayerPrefs.SetInt("naturestaff", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); itemler[item].SetActive(true); alindi = true; okbuton.SetActive(true); }; }
            if (item == 9) { if (PlayerPrefs.GetInt("musketrifle") == 1) { satinalma(); } if (PlayerPrefs.GetInt("musketrifle") == 0) { PlayerPrefs.SetInt("musketrifle", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); itemler[item].SetActive(true); alindi = true; okbuton.SetActive(true); };}
            if (item == 10) { if (PlayerPrefs.GetInt("revolver") == 1) { satinalma(); } if (PlayerPrefs.GetInt("revolver") == 0) { PlayerPrefs.SetInt("revolver", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); itemler[item].SetActive(true); alindi = true; okbuton.SetActive(true); };}
            if (item == 11) { if (PlayerPrefs.GetInt("sai") == 1) { satinalma(); } if (PlayerPrefs.GetInt("sai") == 0) { PlayerPrefs.SetInt("sai", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); itemler[item].SetActive(true); alindi = true; okbuton.SetActive(true); };}
            if (item == 12) { if (PlayerPrefs.GetInt("hammer") == 1) { satinalma(); } if (PlayerPrefs.GetInt("hammer") == 0) { PlayerPrefs.SetInt("hammer", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); itemler[item].SetActive(true); alindi = true; okbuton.SetActive(true); };}
            if (item == 13) { if (PlayerPrefs.GetInt("musketpistol") == 1) { satinalma(); } if (PlayerPrefs.GetInt("musketpistol") == 0) { PlayerPrefs.SetInt("musketpistol", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); itemler[item].SetActive(true); alindi = true; okbuton.SetActive(true); }; }
            if (item == 14) { if (PlayerPrefs.GetInt("naginata") == 1) { satinalma(); } if (PlayerPrefs.GetInt("naginata") == 0) { PlayerPrefs.SetInt("naginata", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); itemler[item].SetActive(true); alindi = true; okbuton.SetActive(true); }; }
            if (item == 15) { if (PlayerPrefs.GetInt("shieldhalf") == 1) { satinalma(); } if (PlayerPrefs.GetInt("shieldhalf") == 0) { PlayerPrefs.SetInt("shieldhalf", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); itemler[item].SetActive(true); alindi = true; okbuton.SetActive(true); };}
            if (item == 16) { if (PlayerPrefs.GetInt("bow") == 1) { satinalma(); } if (PlayerPrefs.GetInt("bow") == 0) { PlayerPrefs.SetInt("bow", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); itemler[item].SetActive(true); alindi = true; okbuton.SetActive(true); };}
            if (item == 17) { if (PlayerPrefs.GetInt("shieldviking") == 1) { satinalma(); } if (PlayerPrefs.GetInt("shieldviking") == 0) { PlayerPrefs.SetInt("shieldviking", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); itemler[item].SetActive(true); alindi = true; okbuton.SetActive(true); }; }
            if (item == 18) { if (PlayerPrefs.GetInt("staff") == 1) { satinalma(); } if (PlayerPrefs.GetInt("staff") == 0) { PlayerPrefs.SetInt("staff", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); itemler[item].SetActive(true); alindi = true; okbuton.SetActive(true); };}
            if (item == 19) { if (PlayerPrefs.GetInt("sword") == 1) { satinalma(); } if (PlayerPrefs.GetInt("sword") == 0) { PlayerPrefs.SetInt("sword", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); itemler[item].SetActive(true); alindi = true; okbuton.SetActive(true); }; }
            if (item == 20) { if (PlayerPrefs.GetInt("katana") == 1) { satinalma(); } if (PlayerPrefs.GetInt("katana") == 0) { PlayerPrefs.SetInt("katana", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); itemler[item].SetActive(true); alindi = true; okbuton.SetActive(true); }; }
            if (item == 21) { if (PlayerPrefs.GetInt("axe") == 1) { satinalma(); } if (PlayerPrefs.GetInt("axe") == 0) { PlayerPrefs.SetInt("axe", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); itemler[item].SetActive(true); alindi = true; okbuton.SetActive(true); }; }
            if (item == 22) { if (PlayerPrefs.GetInt("shieldknight") == 1) { satinalma(); } if (PlayerPrefs.GetInt("shieldknight") == 0) { PlayerPrefs.SetInt("shieldknight", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); itemler[item].SetActive(true); alindi = true; okbuton.SetActive(true); }; }
            if (item == 23) { if (PlayerPrefs.GetInt("swordbroken") == 1) { satinalma(); } if (PlayerPrefs.GetInt("swordbroken") == 0) { PlayerPrefs.SetInt("swordbroken", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); itemler[item].SetActive(true); alindi = true; okbuton.SetActive(true); };}
            if (item == 24) { if (PlayerPrefs.GetInt("saber") == 1) { satinalma(); } if (PlayerPrefs.GetInt("saber") == 0) { PlayerPrefs.SetInt("saber", 1); PlayerPrefs.SetInt("para", PlayerPrefs.GetInt("para") - 5000); Instantiate(kiriksandik, sandik.transform.position, sandik.transform.rotation); Destroy(sandik); itemler[item].SetActive(true);alindi = true; okbuton.SetActive(true); }; }
            if (item > 24) { satinalma(); }
        }
        if (ilksec > 2) { satinalma(); }

    }
    void Update()
    {
        if(alindi == false) {
            if (PlayerPrefs.GetInt("para") > 4999) { satinalmabuton.SetActive(true); }
            else { satinalmabuton.SetActive(false); }
        }
        if (alindi == true) { satinalmabuton.SetActive(false); }
        
        paratext.GetComponent<Text>().text =PlayerPrefs.GetInt("para").ToString();
    }
}
